sudo: false
language: node_js
node_js:
- node
- 10
- 9
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
matrix:
  fast_finish: true
before_install:
- npm i
script:
- npm run ci
- npm run build
notifications:
  email: false
  slack:
    secure: zLUKdI6mmTeaflFUxySE0ZeRTtsTjsnD/b2hoMrxZ28UdDKj48eKkIG/AbUKdrK4v85e/psldFa6VuKkQ4Y2RuDgIEuuKstScQRpFOjyB3rMde+xbPll7F0v8kVOZt+JTBHtk9Q37MpS/uAzrgoQJs469mQ6S9+7M/3SmXw8GhzXSiQtixiN3vS3ieovZwLfVLnpPGU31zk/s5KVtcwy60dzU/el9GRdcWkzJ2vDxzZIniGzrALSSJPlQvVP6NQ3M2tWtHAqDd4IcGzyr7laQwIdvkGVour2JZdRWocficd/LGCiOAH7HZORWjsHU5gn4nLF4UxAil3EyLsjUZzCvHiRcF5kR0CcuB0pgKXDwEfD8AldrPg+U5k9W3glJn0K7X4ycIyJvBi1TfN5vfSOu2IcOet2pL/PtiTnUXt9ePQvsAhIHnd+py4EgIKgNr6kS4JRW6sUEL8QBM/qffOhcmuM7cOuRgMjPNAEaALVEQ3JeiVvkYMzsGJBskPA6xIEc5OcGMuRN1jCw89wjU6ovQS2BxDZLxAxoGXKIFnT8ieLf3jvZUM/0WRwUxhmyaM/FETG/AZy0a+KUYpG2WXXfa3aVoJmhXz0StiWr9+rAF0qosJQilhHiFNHlI8nAH9idtPiVCeA1vy8KzwF2x8Xeph+L265SGBufzVLMPfFaNs=
deploy:
  provider: npm
  email: sebastian@katallaxie.me
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: la5Q18QJ+qOSkAy/b1jc+vQ1oLs1ECuDa+5XT3h7aM9XNMxZInD6egEMc6I4FjCyd5ieZEgCKi3Lus84BXOg2VR2ZKmdKankUVYSXU7pKLlQ5Ee7xPnj6M+FjNLuzq7TGwhgiEtEQgPiTKSZVObAr73OmvuIluO2BjGaeaddZ5wKuBiF2+mtn9pOfJhWp3HaYADoI/nX2ubmefG0d54jxomP5sVUWSUIh4it4oRv6zaIWdlDG2nQmPUkGKNwjC79wi22QqSr9v6K7BkxkTBu8HGpOXw280ebDSP1EpIdhl+Z+C6hrM812U+r4majvwW5oPGofKzndrvJxfBcw3yJDrUrFQe48tOUPcx7D9ewZ29F1vG6kbjn0Dowc71nh+GlH9BTZgBqV4ILB68aU7EMUXCvpB1BDc3zHG9mFKOSYCb7DgurEH8lS4gn6e+H16R5hDa3wAF8f6ZFcBP2xshkFgY0qYrjb5M80rH80G2BjXyvCqBAou2lVUcQ/cfHSpPy/fSUee4Zs4711Nl74tjcRrVglU41Uc8hc3ln4cjVzQyxQWruI1pf3mFx+Z15mYamSOBEq/6K4wmNyNE9/mG3zY3KukvhHgSY3TK+g34jSpS/TsOnjFHobUEMzpm3ADT/sOJugnkb/2HTA6KRWGHMiQKUv+3ggyWsZmZp+A4CAEE=
