sudo: false
language: node_js
node_js:
- node
- 10
- 9
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
matrix:
  fast_finish: true
before_install:
- npm i
script:
- npm run ci
- npm run build
notifications:
  email: false
  slack:
    secure: zLUKdI6mmTeaflFUxySE0ZeRTtsTjsnD/b2hoMrxZ28UdDKj48eKkIG/AbUKdrK4v85e/psldFa6VuKkQ4Y2RuDgIEuuKstScQRpFOjyB3rMde+xbPll7F0v8kVOZt+JTBHtk9Q37MpS/uAzrgoQJs469mQ6S9+7M/3SmXw8GhzXSiQtixiN3vS3ieovZwLfVLnpPGU31zk/s5KVtcwy60dzU/el9GRdcWkzJ2vDxzZIniGzrALSSJPlQvVP6NQ3M2tWtHAqDd4IcGzyr7laQwIdvkGVour2JZdRWocficd/LGCiOAH7HZORWjsHU5gn4nLF4UxAil3EyLsjUZzCvHiRcF5kR0CcuB0pgKXDwEfD8AldrPg+U5k9W3glJn0K7X4ycIyJvBi1TfN5vfSOu2IcOet2pL/PtiTnUXt9ePQvsAhIHnd+py4EgIKgNr6kS4JRW6sUEL8QBM/qffOhcmuM7cOuRgMjPNAEaALVEQ3JeiVvkYMzsGJBskPA6xIEc5OcGMuRN1jCw89wjU6ovQS2BxDZLxAxoGXKIFnT8ieLf3jvZUM/0WRwUxhmyaM/FETG/AZy0a+KUYpG2WXXfa3aVoJmhXz0StiWr9+rAF0qosJQilhHiFNHlI8nAH9idtPiVCeA1vy8KzwF2x8Xeph+L265SGBufzVLMPfFaNs=
