version: "3.2"

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "(cd /fluffy && ./scripts/start.sh)"
    volumes:
      - ./sites.conf:/etc/nginx/sites-available/default
      - .:/fluffy
    image: nginx
    ports:
      - 8080:80
    networks:
      - dev

networks:
  dev:
