import * as mfs from 'memory-fs'
import * as webpack from 'webpack'
import exit from './exit'

export default async (app, config, cb) => {
  let bundle
  let clientManifest
  let template
  let devMiddleware

  const ready = (...args) => {
    cb(...args)
  }

  // modify client config to work with hot middleware
  config.devConfig.output.filename = '[name].js'

  // dev middleware
  const compiler = webpack(config.devConfig)

  try {
    devMiddleware = await require('koa-webpack')({
      compiler,
      config: {
        writeToDisk: !config.noEmit,
        publicPath: config.devConfig.output.publicPath,
        noInfo: true,
        stats: {
          colors: true,
          chunks: false
        },
        // serverSideRender: true
      }
    })
  } catch (err) {
    exit(err)
  }
  app.use(devMiddleware.devMiddleware)
  app.use(devMiddleware.hotClient)

  compiler.plugin('done', () => {
    const fs = devMiddleware.dev.fileSystem
    const readFile = (file) => fs.readFileSync(file, 'utf-8')
    clientManifest = JSON.parse(readFile(config.manifest))
    template = readFile(config.template)
    if (bundle) {
      ready(bundle, template, {
        clientManifest
      })
    }
  })

  // watch and update server renderer
  const serverCompiler = webpack(config.ssrConfig)
  const fs = new mfs()
  serverCompiler.outputFileSystem = fs
  serverCompiler.watch({}, (err, stats) => {
    if (err) {
      throw err
    }
    stats = stats.toJson()
    stats.errors.forEach((er) => console.error(er))
    stats.warnings.forEach((er) => console.warn(er))
    const readFile = (file) => {
      return fs.readFileSync(file, 'utf-8')
    }
    // read bundle generated by vue-ssr-webpack-plugin
    bundle = JSON.parse(readFile(config.bundle))
    if (clientManifest && template) {
      cb(bundle, template, { clientManifest })
    }
  })

  return devMiddleware
}
